# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48202ae618cbdb005758141b2b3e59c6cf219358f5edda4fda22758bd9471826d187e46712b3db0e5067560f3aac5bdf9f8b6bd790744a37c262e96a313fbcdd

test:
  secret_key_base: 7cccdcfe35d0a8d7c4f48563ba83d17ffe83da90568a57d1b35a5ddcc41a31f9e8cf740d50ac1825b4b09c87b6ecdf3cb3678b2013e1be29cbe9525f7962a388

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
