# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 019d5ba9b4d3a3b207800cc51b98826f82fbf1c29894418bae4ee958fb8fa97b8fe4ca96cd5be46f7735f0162be28a4f501ff2d02e834a5202132b1b902cb559

test:
  secret_key_base: 23d5b49665b4996b6d6ca61f067a238b59760fbd4e952a79811ee071c3b102a34da104a9991e8fbce8ced7a264e2fac8045d8708993110467907fc52a3027bac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
